owner: mike-kd2
repo: upptime

sites:
  - name: ndsg-check.ch
    url: https://ndsg-check.ch
    expectedStatusCodes:
      - 200

  - name: Glossar
    url: https://ndsg-check.ch/glossar
    expectedStatusCodes:
      - 200

  - name: Scan Worker
    url: https://scan.ndsg-check.ch/health
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"ok"'

status-website:
  baseUrl: /upptime
  name: nDSG-Check Status
  theme: dark

notifications:
  - type: email
    to: michael@klauserdesigns.ch
  - type: telegram
    botToken: $TELEGRAM_BOT_TOKEN
    chatId: $TELEGRAM_CHAT_ID

workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: "0 0 * * *"

i18n:
  activeIncidents: Aktuelle Störungen
  pastIncidents: Vergangene Störungen
  pastIncidentsResolved: Gelöst
  allSystemsOperational: Alle Systeme laufen
  noIncidents: Keine Störungen
  activeMaintenances: Wartungsarbeiten
  scheduledMaintenances: Geplante Wartungsarbeiten
